export interface PricingItem {
  id: string
  category: string
  name: string
  description: string
  unit: 'sqm' | 'lm' | 'nos' | 'ls' | 'set'
  unitRate: number
  minQty?: number
  maxQty?: number
  isOptional: boolean
  tags: string[]
}

export interface PricingCategory {
  id: string
  name: string
  icon: string
  items: PricingItem[]
}

// Unit rates derived from 6 real commercial proposals (Left Loft / Effekt Design, Dubai)
// Rates represent averaged AED per unit across multiple villa projects

export const pricingCategories: PricingCategory[] = [
  {
    id: 'demolition',
    name: 'Site Preparation',
    icon: '🏗',
    items: [
      {
        id: 'demo-works',
        category: 'demolition',
        name: 'Demolition & Site Clearance',
        description: 'Demolition, mobilization, backfill removal, and site cleanup',
        unit: 'ls',
        unitRate: 12000,
        minQty: 1,
        maxQty: 1,
        isOptional: false,
        tags: ['site-prep'],
      },
    ],
  },
  {
    id: 'flooring',
    name: 'Flooring & Hardscape',
    icon: '🪨',
    items: [
      {
        id: 'floor-pcc-base',
        category: 'flooring',
        name: 'Floor Base Construction (PCC 10cm)',
        description: 'Construction of all floor levels with PCC base (10cm thickness)',
        unit: 'sqm',
        unitRate: 88,
        isOptional: false,
        tags: ['flooring', 'base'],
      },
      {
        id: 'floor-porcelain',
        category: 'flooring',
        name: 'Porcelain Tiles (60×120cm)',
        description: 'Supply & installation of porcelain tile (60×120cm, 2cm thickness) with MAPEI grout',
        unit: 'sqm',
        unitRate: 300,
        isOptional: false,
        tags: ['flooring', 'tiles', 'porcelain'],
      },
      {
        id: 'floor-crazy-stone',
        category: 'flooring',
        name: 'Natural / Crazy Stone Tiles',
        description: 'Supply & installation of Omani natural or crazy stone tiles with MAPEI grout',
        unit: 'sqm',
        unitRate: 580,
        isOptional: true,
        tags: ['flooring', 'stone', 'natural'],
      },
      {
        id: 'floor-artificial-grass',
        category: 'flooring',
        name: 'Artificial Grass (32mm Cushion)',
        description: 'Supply and installation of 32mm thick cushion MAZE artificial grass',
        unit: 'sqm',
        unitRate: 150,
        isOptional: true,
        tags: ['flooring', 'grass', 'softscape'],
      },
      {
        id: 'floor-gravel',
        category: 'flooring',
        name: 'Decorative Gravel',
        description: 'Supply and installation of beige gravel as per design',
        unit: 'sqm',
        unitRate: 68,
        isOptional: true,
        tags: ['flooring', 'gravel', 'natural'],
      },
    ],
  },
  {
    id: 'structures',
    name: 'Outdoor Structures',
    icon: '🏛',
    items: [
      {
        id: 'struct-bbq-counter',
        category: 'structures',
        name: 'BBQ Counter',
        description: 'RCC concrete BBQ counter with porcelain slab finish, aluminum doors, sink with mixer',
        unit: 'ls',
        unitRate: 22000,
        minQty: 1,
        maxQty: 2,
        isOptional: true,
        tags: ['bbq', 'counter', 'outdoor-kitchen'],
      },
      {
        id: 'struct-bar-counter',
        category: 'structures',
        name: 'Bar Counter (with seating)',
        description: 'U-shape bar counter with RCC concrete, porcelain finish, aluminum doors, sink, mixer & ice box',
        unit: 'ls',
        unitRate: 29000,
        minQty: 1,
        maxQty: 1,
        isOptional: true,
        tags: ['bar', 'counter', 'entertainment'],
      },
      {
        id: 'struct-kitchen-counter',
        category: 'structures',
        name: 'Small Kitchen Counter',
        description: 'Outdoor kitchen counter with RCC concrete, porcelain finish, aluminum doors, sink with mixer',
        unit: 'ls',
        unitRate: 10780,
        minQty: 1,
        maxQty: 1,
        isOptional: true,
        tags: ['kitchen', 'counter', 'outdoor-kitchen'],
      },
      {
        id: 'struct-pergola-small',
        category: 'structures',
        name: 'Aluminum Pergola (Small)',
        description: 'White aluminum pergola approx. 190cm × 350cm as per 3D design',
        unit: 'ls',
        unitRate: 7500,
        minQty: 1,
        maxQty: 3,
        isOptional: true,
        tags: ['pergola', 'shade', 'aluminum'],
      },
      {
        id: 'struct-pergola-medium',
        category: 'structures',
        name: 'Aluminum Pergola (Medium)',
        description: 'White aluminum pergola approx. 400cm × 385cm as per 3D design',
        unit: 'ls',
        unitRate: 28000,
        minQty: 1,
        maxQty: 2,
        isOptional: true,
        tags: ['pergola', 'shade', 'aluminum'],
      },
      {
        id: 'struct-pergola-large',
        category: 'structures',
        name: 'Aluminum Pergola (Large)',
        description: 'White aluminum pergola approx. 560cm × 440cm+ as per 3D design',
        unit: 'ls',
        unitRate: 42000,
        minQty: 1,
        maxQty: 2,
        isOptional: true,
        tags: ['pergola', 'shade', 'aluminum'],
      },
      {
        id: 'struct-gazebo',
        category: 'structures',
        name: 'Gazebo (2-side closed)',
        description: '2-side closed gazebo, RCC columns, aluminum wooden finish beams, brick ceiling (approx. 800cm × 600cm)',
        unit: 'ls',
        unitRate: 85000,
        minQty: 1,
        maxQty: 1,
        isOptional: true,
        tags: ['gazebo', 'shade', 'premium'],
      },
      {
        id: 'struct-sunken-gazebo',
        category: 'structures',
        name: 'Sunken Gazebo with Seating',
        description: 'Sunken gazebo with seating bench, concrete, tiling, aluminum white finish pergola with 45° louvers',
        unit: 'ls',
        unitRate: 65000,
        minQty: 1,
        maxQty: 1,
        isOptional: true,
        tags: ['gazebo', 'sunken', 'premium'],
      },
      {
        id: 'struct-cabana',
        category: 'structures',
        name: 'Swimming Pool Cabana',
        description: 'White aluminum cabana/pergola (approx. 300cm × 330cm)',
        unit: 'ls',
        unitRate: 16000,
        minQty: 1,
        maxQty: 2,
        isOptional: true,
        tags: ['cabana', 'pool', 'shade'],
      },
      {
        id: 'struct-car-shade',
        category: 'structures',
        name: 'Electronic Car Shade',
        description: 'Motorized car shade with sail shades as per design',
        unit: 'ls',
        unitRate: 18800,
        minQty: 1,
        maxQty: 2,
        isOptional: true,
        tags: ['car-shade', 'motorized'],
      },
    ],
  },
  {
    id: 'water-features',
    name: 'Water Features',
    icon: '💧',
    items: [
      {
        id: 'water-pool-small',
        category: 'water-features',
        name: 'Swimming Pool (up to 35 sqm)',
        description: 'Skimmer type pool: excavation, RCC, tiling, filtration, pump, lighting, plumbing & electrical',
        unit: 'ls',
        unitRate: 145000,
        minQty: 1,
        maxQty: 1,
        isOptional: true,
        tags: ['pool', 'swimming', 'premium'],
      },
      {
        id: 'water-pool-medium',
        category: 'water-features',
        name: 'Swimming Pool (35–50 sqm)',
        description: 'Skimmer type pool: excavation, RCC, tiling, filtration, pump, lighting, plumbing & electrical',
        unit: 'ls',
        unitRate: 182000,
        minQty: 1,
        maxQty: 1,
        isOptional: true,
        tags: ['pool', 'swimming', 'premium'],
      },
      {
        id: 'water-pool-large',
        category: 'water-features',
        name: 'Swimming Pool (50+ sqm)',
        description: 'Skimmer type pool: excavation, RCC, mosaic tiling, filtration, pump, lighting, plumbing & electrical',
        unit: 'ls',
        unitRate: 242000,
        minQty: 1,
        maxQty: 1,
        isOptional: true,
        tags: ['pool', 'swimming', 'premium'],
      },
      {
        id: 'water-pool-heater',
        category: 'water-features',
        name: 'Pool Heating & Cooling System',
        description: 'A-TECH Inverter heating/cooling system (25–50KW) with all fittings',
        unit: 'ls',
        unitRate: 25000,
        minQty: 1,
        maxQty: 1,
        isOptional: true,
        tags: ['pool', 'heater', 'hvac'],
      },
      {
        id: 'water-jacuzzi',
        category: 'water-features',
        name: 'Jacuzzi',
        description: 'RCC jacuzzi with tiling, bubbler, heater, filtration system, pump & lights',
        unit: 'ls',
        unitRate: 52000,
        minQty: 1,
        maxQty: 1,
        isOptional: true,
        tags: ['jacuzzi', 'pool', 'premium'],
      },
      {
        id: 'water-waterfall',
        category: 'water-features',
        name: 'Decorative Waterfall',
        description: 'Waterfall from stepping stones, porcelain tiles, BOTAMENT waterproofing, silent pump',
        unit: 'ls',
        unitRate: 15000,
        minQty: 1,
        maxQty: 2,
        isOptional: true,
        tags: ['waterfall', 'feature'],
      },
      {
        id: 'water-pool-waterfall',
        category: 'water-features',
        name: 'Pool Waterfall Feature',
        description: 'Pool waterfall with porcelain tiles, waterproofing, and separate pump',
        unit: 'ls',
        unitRate: 9240,
        minQty: 1,
        maxQty: 1,
        isOptional: true,
        tags: ['waterfall', 'pool'],
      },
    ],
  },
  {
    id: 'landscaping',
    name: 'Soft Landscaping',
    icon: '🌿',
    items: [
      {
        id: 'land-planter-boxes',
        category: 'landscaping',
        name: 'Planter Boxes',
        description: 'Built planter boxes with stepping stones, porcelain tiles, BOTAMENT waterproofing, planting soil',
        unit: 'lm',
        unitRate: 980,
        isOptional: true,
        tags: ['planter', 'softscape'],
      },
      {
        id: 'land-irrigation',
        category: 'landscaping',
        name: 'Automatic Irrigation System',
        description: 'Automatic irrigation with balance system for all plants',
        unit: 'ls',
        unitRate: 6500,
        minQty: 1,
        maxQty: 1,
        isOptional: false,
        tags: ['irrigation', 'planting'],
      },
    ],
  },
  {
    id: 'built-elements',
    name: 'Built Elements',
    icon: '🧱',
    items: [
      {
        id: 'built-seating-bench',
        category: 'built-elements',
        name: 'Built-in Seating Bench',
        description: 'Concrete seating bench with smoothing and painting/tiling as per 3D design',
        unit: 'ls',
        unitRate: 10500,
        minQty: 1,
        maxQty: 4,
        isOptional: true,
        tags: ['seating', 'bench'],
      },
      {
        id: 'built-seating-tiled',
        category: 'built-elements',
        name: 'Built-in Seats (Tiled)',
        description: 'Built-in seats with stepping stones, porcelain tiles finish',
        unit: 'ls',
        unitRate: 16250,
        minQty: 1,
        maxQty: 2,
        isOptional: true,
        tags: ['seating', 'bench', 'premium'],
      },
      {
        id: 'built-boundary-wall',
        category: 'built-elements',
        name: 'Boundary Wall',
        description: 'Concrete boundary wall with smoothing cement and painting',
        unit: 'nos',
        unitRate: 8000,
        minQty: 1,
        maxQty: 5,
        isOptional: true,
        tags: ['wall', 'boundary', 'privacy'],
      },
      {
        id: 'built-arch-wall',
        category: 'built-elements',
        name: 'Feature Arch Wall',
        description: 'RCC wall with arches and crazy stone tiling (approx. 500cm × 200cm)',
        unit: 'ls',
        unitRate: 15400,
        minQty: 1,
        maxQty: 1,
        isOptional: true,
        tags: ['wall', 'feature', 'arch'],
      },
      {
        id: 'built-shower',
        category: 'built-elements',
        name: 'Outdoor Shower',
        description: 'Shower wall with porcelain tiles and new fittings',
        unit: 'ls',
        unitRate: 7800,
        minQty: 1,
        maxQty: 2,
        isOptional: true,
        tags: ['shower', 'pool'],
      },
      {
        id: 'built-garden-gate',
        category: 'built-elements',
        name: 'Garden Gate',
        description: 'White aluminum door/gate as per design',
        unit: 'nos',
        unitRate: 3500,
        minQty: 1,
        maxQty: 4,
        isOptional: true,
        tags: ['gate', 'door', 'access'],
      },
      {
        id: 'built-kids-play',
        category: 'built-elements',
        name: 'Kids Play Area',
        description: 'Dedicated kids play area installation',
        unit: 'ls',
        unitRate: 15200,
        minQty: 1,
        maxQty: 1,
        isOptional: true,
        tags: ['kids', 'play', 'family'],
      },
    ],
  },
  {
    id: 'electrical',
    name: 'Lighting & Electrical',
    icon: '💡',
    items: [
      {
        id: 'elec-main-installation',
        category: 'electrical',
        name: 'Main Electrical Installation',
        description: 'New DB, junction boxes, conduit, and wiring for all garden lighting and services',
        unit: 'ls',
        unitRate: 18500,
        minQty: 1,
        maxQty: 1,
        isOptional: false,
        tags: ['electrical', 'installation'],
      },
      {
        id: 'elec-spike-lights',
        category: 'electrical',
        name: 'Tree Spike Lights (12W)',
        description: 'Tree enhancer spike light 12W, 3000K, powder-coated bronze, IP66, 2yr warranty',
        unit: 'nos',
        unitRate: 222,
        minQty: 5,
        maxQty: 40,
        isOptional: true,
        tags: ['lighting', 'spike', 'tree'],
      },
      {
        id: 'elec-wall-lights',
        category: 'electrical',
        name: 'Up & Down Wall Lights',
        description: '3000K wall light, acrylic beam, IP65, 2yr warranty',
        unit: 'nos',
        unitRate: 250,
        minQty: 4,
        maxQty: 30,
        isOptional: true,
        tags: ['lighting', 'wall'],
      },
      {
        id: 'elec-recessed-lights',
        category: 'electrical',
        name: 'LED Recessed Lights (Pergola)',
        description: '12V recessed LED, 3000K, aluminum, IP68, 1yr warranty',
        unit: 'nos',
        unitRate: 55,
        minQty: 10,
        maxQty: 50,
        isOptional: true,
        tags: ['lighting', 'recessed', 'pergola'],
      },
      {
        id: 'elec-hanging-lights',
        category: 'electrical',
        name: 'Hanging Decorative Lights',
        description: '110-240V, E27 base, 3000K, decorative pendant style',
        unit: 'nos',
        unitRate: 370,
        minQty: 1,
        maxQty: 6,
        isOptional: true,
        tags: ['lighting', 'decorative', 'hanging'],
      },
      {
        id: 'elec-led-strip',
        category: 'electrical',
        name: 'LED Strip Lighting',
        description: '12V LED strip, 3000K warm white',
        unit: 'lm',
        unitRate: 100,
        minQty: 5,
        maxQty: 80,
        isOptional: true,
        tags: ['lighting', 'strip', 'led'],
      },
    ],
  },
  {
    id: 'management',
    name: 'Project Management',
    icon: '📋',
    items: [
      {
        id: 'mgmt-fees',
        category: 'management',
        name: 'Management & Logistics',
        description: 'Project management fees, logistics and transportation',
        unit: 'ls',
        unitRate: 18000,
        minQty: 1,
        maxQty: 1,
        isOptional: false,
        tags: ['management', 'logistics'],
      },
    ],
  },
]

export const VAT_RATE = 0.05

export const allPricingItems: PricingItem[] = pricingCategories.flatMap(c => c.items)

export function getPricingItem(id: string): PricingItem | undefined {
  return allPricingItems.find(item => item.id === id)
}

export function calculateLineTotal(unitRate: number, quantity: number): number {
  return Math.round(unitRate * quantity)
}

export function calculateSubtotal(lines: { unitRate: number; quantity: number }[]): number {
  return lines.reduce((sum, line) => sum + calculateLineTotal(line.unitRate, line.quantity), 0)
}

export function calculateVAT(subtotal: number): number {
  return Math.round(subtotal * VAT_RATE)
}

export function calculateGrandTotal(subtotal: number): number {
  return subtotal + calculateVAT(subtotal)
}

export function formatAED(amount: number): string {
  return `AED ${amount.toLocaleString('en-US')}`
}
